package cn.entity;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_id
     *
     * @mbggenerated
     */
    private Integer commentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_content
     *
     * @mbggenerated
     */
    private String commentsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_house
     *
     * @mbggenerated
     */
    private Integer commentsHouse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_id
     *
     * @return the value of comments.comments_id
     *
     * @mbggenerated
     */
    public Integer getCommentsId() {
        return commentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_id
     *
     * @param commentsId the value for comments.comments_id
     *
     * @mbggenerated
     */
    public void setCommentsId(Integer commentsId) {
        this.commentsId = commentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_content
     *
     * @return the value of comments.comments_content
     *
     * @mbggenerated
     */
    public String getCommentsContent() {
        return commentsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_content
     *
     * @param commentsContent the value for comments.comments_content
     *
     * @mbggenerated
     */
    public void setCommentsContent(String commentsContent) {
        this.commentsContent = commentsContent == null ? null : commentsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_house
     *
     * @return the value of comments.comments_house
     *
     * @mbggenerated
     */
    public Integer getCommentsHouse() {
        return commentsHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_house
     *
     * @param commentsHouse the value for comments.comments_house
     *
     * @mbggenerated
     */
    public void setCommentsHouse(Integer commentsHouse) {
        this.commentsHouse = commentsHouse;
    }
}