package cn.entity;

import java.util.Date;

public class Custom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_id
     *
     * @mbggenerated
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_name
     *
     * @mbggenerated
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_phone
     *
     * @mbggenerated
     */
    private Integer customPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_state
     *
     * @mbggenerated
     */
    private String customState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_date
     *
     * @mbggenerated
     */
    private Date customDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_min_acreage
     *
     * @mbggenerated
     */
    private Integer customMinAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_max_acreage
     *
     * @mbggenerated
     */
    private Integer customMaxAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_property_id
     *
     * @mbggenerated
     */
    private Integer customPropertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_school_id
     *
     * @mbggenerated
     */
    private Integer customSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_village_id
     *
     * @mbggenerated
     */
    private Integer customVillageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_decoration
     *
     * @mbggenerated
     */
    private String customDecoration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_room
     *
     * @mbggenerated
     */
    private Integer customRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_user_id
     *
     * @mbggenerated
     */
    private Integer customUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_property_use
     *
     * @mbggenerated
     */
    private String customPropertyUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_compeleted_min_year
     *
     * @mbggenerated
     */
    private Date customCompeletedMinYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_compeleted_max_year
     *
     * @mbggenerated
     */
    private Date customCompeletedMaxYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_comments_id
     *
     * @mbggenerated
     */
    private Integer customCommentsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_id
     *
     * @return the value of custom.custom_id
     *
     * @mbggenerated
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_id
     *
     * @param customId the value for custom.custom_id
     *
     * @mbggenerated
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_name
     *
     * @return the value of custom.custom_name
     *
     * @mbggenerated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_name
     *
     * @param customName the value for custom.custom_name
     *
     * @mbggenerated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_phone
     *
     * @return the value of custom.custom_phone
     *
     * @mbggenerated
     */
    public Integer getCustomPhone() {
        return customPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_phone
     *
     * @param customPhone the value for custom.custom_phone
     *
     * @mbggenerated
     */
    public void setCustomPhone(Integer customPhone) {
        this.customPhone = customPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_state
     *
     * @return the value of custom.custom_state
     *
     * @mbggenerated
     */
    public String getCustomState() {
        return customState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_state
     *
     * @param customState the value for custom.custom_state
     *
     * @mbggenerated
     */
    public void setCustomState(String customState) {
        this.customState = customState == null ? null : customState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_date
     *
     * @return the value of custom.custom_date
     *
     * @mbggenerated
     */
    public Date getCustomDate() {
        return customDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_date
     *
     * @param customDate the value for custom.custom_date
     *
     * @mbggenerated
     */
    public void setCustomDate(Date customDate) {
        this.customDate = customDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_min_acreage
     *
     * @return the value of custom.custom_min_acreage
     *
     * @mbggenerated
     */
    public Integer getCustomMinAcreage() {
        return customMinAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_min_acreage
     *
     * @param customMinAcreage the value for custom.custom_min_acreage
     *
     * @mbggenerated
     */
    public void setCustomMinAcreage(Integer customMinAcreage) {
        this.customMinAcreage = customMinAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_max_acreage
     *
     * @return the value of custom.custom_max_acreage
     *
     * @mbggenerated
     */
    public Integer getCustomMaxAcreage() {
        return customMaxAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_max_acreage
     *
     * @param customMaxAcreage the value for custom.custom_max_acreage
     *
     * @mbggenerated
     */
    public void setCustomMaxAcreage(Integer customMaxAcreage) {
        this.customMaxAcreage = customMaxAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_property_id
     *
     * @return the value of custom.custom_property_id
     *
     * @mbggenerated
     */
    public Integer getCustomPropertyId() {
        return customPropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_property_id
     *
     * @param customPropertyId the value for custom.custom_property_id
     *
     * @mbggenerated
     */
    public void setCustomPropertyId(Integer customPropertyId) {
        this.customPropertyId = customPropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_school_id
     *
     * @return the value of custom.custom_school_id
     *
     * @mbggenerated
     */
    public Integer getCustomSchoolId() {
        return customSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_school_id
     *
     * @param customSchoolId the value for custom.custom_school_id
     *
     * @mbggenerated
     */
    public void setCustomSchoolId(Integer customSchoolId) {
        this.customSchoolId = customSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_village_id
     *
     * @return the value of custom.custom_village_id
     *
     * @mbggenerated
     */
    public Integer getCustomVillageId() {
        return customVillageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_village_id
     *
     * @param customVillageId the value for custom.custom_village_id
     *
     * @mbggenerated
     */
    public void setCustomVillageId(Integer customVillageId) {
        this.customVillageId = customVillageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_decoration
     *
     * @return the value of custom.custom_decoration
     *
     * @mbggenerated
     */
    public String getCustomDecoration() {
        return customDecoration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_decoration
     *
     * @param customDecoration the value for custom.custom_decoration
     *
     * @mbggenerated
     */
    public void setCustomDecoration(String customDecoration) {
        this.customDecoration = customDecoration == null ? null : customDecoration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_room
     *
     * @return the value of custom.custom_room
     *
     * @mbggenerated
     */
    public Integer getCustomRoom() {
        return customRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_room
     *
     * @param customRoom the value for custom.custom_room
     *
     * @mbggenerated
     */
    public void setCustomRoom(Integer customRoom) {
        this.customRoom = customRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_user_id
     *
     * @return the value of custom.custom_user_id
     *
     * @mbggenerated
     */
    public Integer getCustomUserId() {
        return customUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_user_id
     *
     * @param customUserId the value for custom.custom_user_id
     *
     * @mbggenerated
     */
    public void setCustomUserId(Integer customUserId) {
        this.customUserId = customUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_property_use
     *
     * @return the value of custom.custom_property_use
     *
     * @mbggenerated
     */
    public String getCustomPropertyUse() {
        return customPropertyUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_property_use
     *
     * @param customPropertyUse the value for custom.custom_property_use
     *
     * @mbggenerated
     */
    public void setCustomPropertyUse(String customPropertyUse) {
        this.customPropertyUse = customPropertyUse == null ? null : customPropertyUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_compeleted_min_year
     *
     * @return the value of custom.custom_compeleted_min_year
     *
     * @mbggenerated
     */
    public Date getCustomCompeletedMinYear() {
        return customCompeletedMinYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_compeleted_min_year
     *
     * @param customCompeletedMinYear the value for custom.custom_compeleted_min_year
     *
     * @mbggenerated
     */
    public void setCustomCompeletedMinYear(Date customCompeletedMinYear) {
        this.customCompeletedMinYear = customCompeletedMinYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_compeleted_max_year
     *
     * @return the value of custom.custom_compeleted_max_year
     *
     * @mbggenerated
     */
    public Date getCustomCompeletedMaxYear() {
        return customCompeletedMaxYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_compeleted_max_year
     *
     * @param customCompeletedMaxYear the value for custom.custom_compeleted_max_year
     *
     * @mbggenerated
     */
    public void setCustomCompeletedMaxYear(Date customCompeletedMaxYear) {
        this.customCompeletedMaxYear = customCompeletedMaxYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_comments_id
     *
     * @return the value of custom.custom_comments_id
     *
     * @mbggenerated
     */
    public Integer getCustomCommentsId() {
        return customCommentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_comments_id
     *
     * @param customCommentsId the value for custom.custom_comments_id
     *
     * @mbggenerated
     */
    public void setCustomCommentsId(Integer customCommentsId) {
        this.customCommentsId = customCommentsId;
    }
}