package cn.entity;

public class CustomTrail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_trail.custom_trail_id
     *
     * @mbggenerated
     */
    private Integer customTrailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_trail.custom_state
     *
     * @mbggenerated
     */
    private String customState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_trail.custom_trail
     *
     * @mbggenerated
     */
    private String customTrail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_trail.custom_trail_id
     *
     * @return the value of custom_trail.custom_trail_id
     *
     * @mbggenerated
     */
    public Integer getCustomTrailId() {
        return customTrailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_trail.custom_trail_id
     *
     * @param customTrailId the value for custom_trail.custom_trail_id
     *
     * @mbggenerated
     */
    public void setCustomTrailId(Integer customTrailId) {
        this.customTrailId = customTrailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_trail.custom_state
     *
     * @return the value of custom_trail.custom_state
     *
     * @mbggenerated
     */
    public String getCustomState() {
        return customState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_trail.custom_state
     *
     * @param customState the value for custom_trail.custom_state
     *
     * @mbggenerated
     */
    public void setCustomState(String customState) {
        this.customState = customState == null ? null : customState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_trail.custom_trail
     *
     * @return the value of custom_trail.custom_trail
     *
     * @mbggenerated
     */
    public String getCustomTrail() {
        return customTrail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_trail.custom_trail
     *
     * @param customTrail the value for custom_trail.custom_trail
     *
     * @mbggenerated
     */
    public void setCustomTrail(String customTrail) {
        this.customTrail = customTrail == null ? null : customTrail.trim();
    }
}