package cn.entity;

public class Host {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_id
     *
     * @mbggenerated
     */
    private Integer hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_name
     *
     * @mbggenerated
     */
    private String hostName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_phone
     *
     * @mbggenerated
     */
    private Integer hostPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_address
     *
     * @mbggenerated
     */
    private String hostAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_id
     *
     * @return the value of host.host_id
     *
     * @mbggenerated
     */
    public Integer getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_id
     *
     * @param hostId the value for host.host_id
     *
     * @mbggenerated
     */
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_name
     *
     * @return the value of host.host_name
     *
     * @mbggenerated
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_name
     *
     * @param hostName the value for host.host_name
     *
     * @mbggenerated
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_phone
     *
     * @return the value of host.host_phone
     *
     * @mbggenerated
     */
    public Integer getHostPhone() {
        return hostPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_phone
     *
     * @param hostPhone the value for host.host_phone
     *
     * @mbggenerated
     */
    public void setHostPhone(Integer hostPhone) {
        this.hostPhone = hostPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_address
     *
     * @return the value of host.host_address
     *
     * @mbggenerated
     */
    public String getHostAddress() {
        return hostAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_address
     *
     * @param hostAddress the value for host.host_address
     *
     * @mbggenerated
     */
    public void setHostAddress(String hostAddress) {
        this.hostAddress = hostAddress == null ? null : hostAddress.trim();
    }
}