package cn.entity;

import java.util.Date;

public class HouseMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_id
     *
     * @mbggenerated
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_host_id
     *
     * @mbggenerated
     */
    private Integer houseHostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_date
     *
     * @mbggenerated
     */
    private Date houseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_state
     *
     * @mbggenerated
     */
    private String houseState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_property_id
     *
     * @mbggenerated
     */
    private Integer housePropertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_type
     *
     * @mbggenerated
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_acreage
     *
     * @mbggenerated
     */
    private Integer houseAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_floor
     *
     * @mbggenerated
     */
    private String houseFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_contract_id
     *
     * @mbggenerated
     */
    private Integer houseContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_user_id
     *
     * @mbggenerated
     */
    private Integer houseUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_village＿id
     *
     * @mbggenerated
     */
    private Integer houseVillage＿id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_school_id
     *
     * @mbggenerated
     */
    private Integer houseSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_property_type
     *
     * @mbggenerated
     */
    private String housePropertyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_property_use
     *
     * @mbggenerated
     */
    private String housePropertyUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_room
     *
     * @mbggenerated
     */
    private Integer houseRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_msg.house_compeleted_year
     *
     * @mbggenerated
     */
    private Date houseCompeletedYear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_id
     *
     * @return the value of house_msg.house_id
     *
     * @mbggenerated
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_id
     *
     * @param houseId the value for house_msg.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_host_id
     *
     * @return the value of house_msg.house_host_id
     *
     * @mbggenerated
     */
    public Integer getHouseHostId() {
        return houseHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_host_id
     *
     * @param houseHostId the value for house_msg.house_host_id
     *
     * @mbggenerated
     */
    public void setHouseHostId(Integer houseHostId) {
        this.houseHostId = houseHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_date
     *
     * @return the value of house_msg.house_date
     *
     * @mbggenerated
     */
    public Date getHouseDate() {
        return houseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_date
     *
     * @param houseDate the value for house_msg.house_date
     *
     * @mbggenerated
     */
    public void setHouseDate(Date houseDate) {
        this.houseDate = houseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_state
     *
     * @return the value of house_msg.house_state
     *
     * @mbggenerated
     */
    public String getHouseState() {
        return houseState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_state
     *
     * @param houseState the value for house_msg.house_state
     *
     * @mbggenerated
     */
    public void setHouseState(String houseState) {
        this.houseState = houseState == null ? null : houseState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_property_id
     *
     * @return the value of house_msg.house_property_id
     *
     * @mbggenerated
     */
    public Integer getHousePropertyId() {
        return housePropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_property_id
     *
     * @param housePropertyId the value for house_msg.house_property_id
     *
     * @mbggenerated
     */
    public void setHousePropertyId(Integer housePropertyId) {
        this.housePropertyId = housePropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_type
     *
     * @return the value of house_msg.house_type
     *
     * @mbggenerated
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_type
     *
     * @param houseType the value for house_msg.house_type
     *
     * @mbggenerated
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_acreage
     *
     * @return the value of house_msg.house_acreage
     *
     * @mbggenerated
     */
    public Integer getHouseAcreage() {
        return houseAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_acreage
     *
     * @param houseAcreage the value for house_msg.house_acreage
     *
     * @mbggenerated
     */
    public void setHouseAcreage(Integer houseAcreage) {
        this.houseAcreage = houseAcreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_floor
     *
     * @return the value of house_msg.house_floor
     *
     * @mbggenerated
     */
    public String getHouseFloor() {
        return houseFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_floor
     *
     * @param houseFloor the value for house_msg.house_floor
     *
     * @mbggenerated
     */
    public void setHouseFloor(String houseFloor) {
        this.houseFloor = houseFloor == null ? null : houseFloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_contract_id
     *
     * @return the value of house_msg.house_contract_id
     *
     * @mbggenerated
     */
    public Integer getHouseContractId() {
        return houseContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_contract_id
     *
     * @param houseContractId the value for house_msg.house_contract_id
     *
     * @mbggenerated
     */
    public void setHouseContractId(Integer houseContractId) {
        this.houseContractId = houseContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_user_id
     *
     * @return the value of house_msg.house_user_id
     *
     * @mbggenerated
     */
    public Integer getHouseUserId() {
        return houseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_user_id
     *
     * @param houseUserId the value for house_msg.house_user_id
     *
     * @mbggenerated
     */
    public void setHouseUserId(Integer houseUserId) {
        this.houseUserId = houseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_village＿id
     *
     * @return the value of house_msg.house_village＿id
     *
     * @mbggenerated
     */
    public Integer getHouseVillage＿id() {
        return houseVillage＿id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_village＿id
     *
     * @param houseVillage＿id the value for house_msg.house_village＿id
     *
     * @mbggenerated
     */
    public void setHouseVillage＿id(Integer houseVillage＿id) {
        this.houseVillage＿id = houseVillage＿id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_school_id
     *
     * @return the value of house_msg.house_school_id
     *
     * @mbggenerated
     */
    public Integer getHouseSchoolId() {
        return houseSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_school_id
     *
     * @param houseSchoolId the value for house_msg.house_school_id
     *
     * @mbggenerated
     */
    public void setHouseSchoolId(Integer houseSchoolId) {
        this.houseSchoolId = houseSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_property_type
     *
     * @return the value of house_msg.house_property_type
     *
     * @mbggenerated
     */
    public String getHousePropertyType() {
        return housePropertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_property_type
     *
     * @param housePropertyType the value for house_msg.house_property_type
     *
     * @mbggenerated
     */
    public void setHousePropertyType(String housePropertyType) {
        this.housePropertyType = housePropertyType == null ? null : housePropertyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_property_use
     *
     * @return the value of house_msg.house_property_use
     *
     * @mbggenerated
     */
    public String getHousePropertyUse() {
        return housePropertyUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_property_use
     *
     * @param housePropertyUse the value for house_msg.house_property_use
     *
     * @mbggenerated
     */
    public void setHousePropertyUse(String housePropertyUse) {
        this.housePropertyUse = housePropertyUse == null ? null : housePropertyUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_room
     *
     * @return the value of house_msg.house_room
     *
     * @mbggenerated
     */
    public Integer getHouseRoom() {
        return houseRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_room
     *
     * @param houseRoom the value for house_msg.house_room
     *
     * @mbggenerated
     */
    public void setHouseRoom(Integer houseRoom) {
        this.houseRoom = houseRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_msg.house_compeleted_year
     *
     * @return the value of house_msg.house_compeleted_year
     *
     * @mbggenerated
     */
    public Date getHouseCompeletedYear() {
        return houseCompeletedYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_msg.house_compeleted_year
     *
     * @param houseCompeletedYear the value for house_msg.house_compeleted_year
     *
     * @mbggenerated
     */
    public void setHouseCompeletedYear(Date houseCompeletedYear) {
        this.houseCompeletedYear = houseCompeletedYear;
    }
}