package cn.entity;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_content
     *
     * @mbggenerated
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_user
     *
     * @mbggenerated
     */
    private Integer newsUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_content
     *
     * @return the value of news.news_content
     *
     * @mbggenerated
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_content
     *
     * @param newsContent the value for news.news_content
     *
     * @mbggenerated
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_user
     *
     * @return the value of news.news_user
     *
     * @mbggenerated
     */
    public Integer getNewsUser() {
        return newsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_user
     *
     * @param newsUser the value for news.news_user
     *
     * @mbggenerated
     */
    public void setNewsUser(Integer newsUser) {
        this.newsUser = newsUser;
    }
}