package cn.entity;

public class Parameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.parameter_id
     *
     * @mbggenerated
     */
    private Integer parameterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.usermgr
     *
     * @mbggenerated
     */
    private Integer usermgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.housemgr
     *
     * @mbggenerated
     */
    private Integer housemgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.contractmgr
     *
     * @mbggenerated
     */
    private Integer contractmgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.salemgr
     *
     * @mbggenerated
     */
    private Integer salemgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.newsmgr
     *
     * @mbggenerated
     */
    private Integer newsmgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.maps
     *
     * @mbggenerated
     */
    private Integer maps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.custom_trail
     *
     * @mbggenerated
     */
    private Integer customTrail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.parameter_id
     *
     * @return the value of parameter.parameter_id
     *
     * @mbggenerated
     */
    public Integer getParameterId() {
        return parameterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.parameter_id
     *
     * @param parameterId the value for parameter.parameter_id
     *
     * @mbggenerated
     */
    public void setParameterId(Integer parameterId) {
        this.parameterId = parameterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.usermgr
     *
     * @return the value of parameter.usermgr
     *
     * @mbggenerated
     */
    public Integer getUsermgr() {
        return usermgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.usermgr
     *
     * @param usermgr the value for parameter.usermgr
     *
     * @mbggenerated
     */
    public void setUsermgr(Integer usermgr) {
        this.usermgr = usermgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.housemgr
     *
     * @return the value of parameter.housemgr
     *
     * @mbggenerated
     */
    public Integer getHousemgr() {
        return housemgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.housemgr
     *
     * @param housemgr the value for parameter.housemgr
     *
     * @mbggenerated
     */
    public void setHousemgr(Integer housemgr) {
        this.housemgr = housemgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.contractmgr
     *
     * @return the value of parameter.contractmgr
     *
     * @mbggenerated
     */
    public Integer getContractmgr() {
        return contractmgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.contractmgr
     *
     * @param contractmgr the value for parameter.contractmgr
     *
     * @mbggenerated
     */
    public void setContractmgr(Integer contractmgr) {
        this.contractmgr = contractmgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.salemgr
     *
     * @return the value of parameter.salemgr
     *
     * @mbggenerated
     */
    public Integer getSalemgr() {
        return salemgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.salemgr
     *
     * @param salemgr the value for parameter.salemgr
     *
     * @mbggenerated
     */
    public void setSalemgr(Integer salemgr) {
        this.salemgr = salemgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.newsmgr
     *
     * @return the value of parameter.newsmgr
     *
     * @mbggenerated
     */
    public Integer getNewsmgr() {
        return newsmgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.newsmgr
     *
     * @param newsmgr the value for parameter.newsmgr
     *
     * @mbggenerated
     */
    public void setNewsmgr(Integer newsmgr) {
        this.newsmgr = newsmgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.maps
     *
     * @return the value of parameter.maps
     *
     * @mbggenerated
     */
    public Integer getMaps() {
        return maps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.maps
     *
     * @param maps the value for parameter.maps
     *
     * @mbggenerated
     */
    public void setMaps(Integer maps) {
        this.maps = maps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.custom_trail
     *
     * @return the value of parameter.custom_trail
     *
     * @mbggenerated
     */
    public Integer getCustomTrail() {
        return customTrail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.custom_trail
     *
     * @param customTrail the value for parameter.custom_trail
     *
     * @mbggenerated
     */
    public void setCustomTrail(Integer customTrail) {
        this.customTrail = customTrail;
    }
}