package cn.entity;

public class Property {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_id
     *
     * @mbggenerated
     */
    private Integer propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_name
     *
     * @mbggenerated
     */
    private String propertyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_id
     *
     * @return the value of property.property_id
     *
     * @mbggenerated
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_id
     *
     * @param propertyId the value for property.property_id
     *
     * @mbggenerated
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_name
     *
     * @return the value of property.property_name
     *
     * @mbggenerated
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_name
     *
     * @param propertyName the value for property.property_name
     *
     * @mbggenerated
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }
}