package cn.entity;

public class School {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.shcool_name
     *
     * @mbggenerated
     */
    private String shcoolName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.school_id
     *
     * @return the value of school.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.school_id
     *
     * @param schoolId the value for school.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.shcool_name
     *
     * @return the value of school.shcool_name
     *
     * @mbggenerated
     */
    public String getShcoolName() {
        return shcoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.shcool_name
     *
     * @param shcoolName the value for school.shcool_name
     *
     * @mbggenerated
     */
    public void setShcoolName(String shcoolName) {
        this.shcoolName = shcoolName == null ? null : shcoolName.trim();
    }
}