package cn.entity;

public class Sell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell.sell_id
     *
     * @mbggenerated
     */
    private Integer sellId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell.sell_paid
     *
     * @mbggenerated
     */
    private Integer sellPaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell.sell_id
     *
     * @return the value of sell.sell_id
     *
     * @mbggenerated
     */
    public Integer getSellId() {
        return sellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell.sell_id
     *
     * @param sellId the value for sell.sell_id
     *
     * @mbggenerated
     */
    public void setSellId(Integer sellId) {
        this.sellId = sellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell.sell_paid
     *
     * @return the value of sell.sell_paid
     *
     * @mbggenerated
     */
    public Integer getSellPaid() {
        return sellPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell.sell_paid
     *
     * @param sellPaid the value for sell.sell_paid
     *
     * @mbggenerated
     */
    public void setSellPaid(Integer sellPaid) {
        this.sellPaid = sellPaid;
    }
}