package cn.entity;

public class Village {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village.village_id
     *
     * @mbggenerated
     */
    private Integer villageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village.village_name
     *
     * @mbggenerated
     */
    private String villageName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village.village_id
     *
     * @return the value of village.village_id
     *
     * @mbggenerated
     */
    public Integer getVillageId() {
        return villageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village.village_id
     *
     * @param villageId the value for village.village_id
     *
     * @mbggenerated
     */
    public void setVillageId(Integer villageId) {
        this.villageId = villageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village.village_name
     *
     * @return the value of village.village_name
     *
     * @mbggenerated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village.village_name
     *
     * @param villageName the value for village.village_name
     *
     * @mbggenerated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }
}