package cn.dao;

import cn.entity.CustomTrail;

public interface CustomTrailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_trail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer customTrailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_trail
     *
     * @mbggenerated
     */
    int insert(CustomTrail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_trail
     *
     * @mbggenerated
     */
    int insertSelective(CustomTrail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_trail
     *
     * @mbggenerated
     */
    CustomTrail selectByPrimaryKey(Integer customTrailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_trail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomTrail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_trail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomTrail record);
}