package cn.dao;

import cn.entity.HouseTrail;

public interface HouseTrailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_trail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer houseTrail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_trail
     *
     * @mbggenerated
     */
    int insert(HouseTrail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_trail
     *
     * @mbggenerated
     */
    int insertSelective(HouseTrail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_trail
     *
     * @mbggenerated
     */
    HouseTrail selectByPrimaryKey(Integer houseTrail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_trail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseTrail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_trail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseTrail record);
}