package cn.dao;

import cn.entity.Parameter;

public interface ParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer parameterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbggenerated
     */
    int insert(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbggenerated
     */
    int insertSelective(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbggenerated
     */
    Parameter selectByPrimaryKey(Integer parameterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parameter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Parameter record);
}