package cn.dao;

import cn.entity.Sell;

public interface SellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sellId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated
     */
    int insert(Sell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated
     */
    int insertSelective(Sell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated
     */
    Sell selectByPrimaryKey(Integer sellId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sell record);
}