package cn.dao;

import cn.entity.Village;

public interface VillageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer villageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village
     *
     * @mbggenerated
     */
    int insert(Village record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village
     *
     * @mbggenerated
     */
    int insertSelective(Village record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village
     *
     * @mbggenerated
     */
    Village selectByPrimaryKey(Integer villageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Village record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Village record);
}